### ISSUE TITLE
Config: Pull Config from File

### ISSUE THREAD

**Issue by jcbwlkr** [jcbwlkr/posthydra#5]
We want users to define their usernames/passwords/API keys etc in some config file and then pull that in when they start the app. One option I've used effectively is `code.google.com/p/gcfg`. We could also look at other options like just parsing a YAML file or a dotenv kind of deal.

**Comment by hitjim** [comment]
Resolved by PR #6

**Comment by hitjim** [comment]
Was this reopened, or did I not close it?  I've lost my mind.

**Comment by jcbwlkr** [comment]
Maybe you just commented but didn't "close and comment?" Either way I'll close it now.
