### ISSUE TITLE
I don't know what to work on next

### ISSUE THREAD

**Issue by hitjim** [jcbwlkr/posthydra#7]
:stuck_out_tongue_winking_eye:

**Comment by hitjim** [comment]
blewp

**Comment by jcbwlkr** [comment]
Some new issues have been filed (^_^). Be sure to claim whatever you want to prevent duplication of work

**Comment by hitjim** [comment]
Oh glorious day!  I'll call one out only if I'm actually sitting down to work on it.  THX.
